export const testHelpers = {
	initialBoardLayoutArray: [
		["bR", "bN", "bB", "bQ", "bK", "bB", "bN", "bR"],
		["bP", "bP", "bP", "bP", "bP", "bP", "bP", "bP"],
		["", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", ""],
		["wP", "wP", "wP", "wP", "wP", "wP", "wP", "wP"],
		["wR", "wN", "wB", "wQ", "wK", "wB", "wN", "wR"],
	],
	fenStringExampleOne: [
		["bR", "bN", "bB", "bQ", "bK", "bB", "bN", "bR"],
		["bP", "bP", "", "bP", "bP", "bP", "bP", "bP"],
		["", "", "", "", "", "", "", ""],
		["", "", "bP", "", "", "", "", ""],
		["", "", "", "", "wP", "", "", ""],
		["", "", "", "", "", "", "", ""],
		["wP", "wP", "wP", "wP", "", "wP", "wP", "wP"],
		["wR", "wN", "wB", "wQ", "wK", "wB", "wN", "wR"],
	],
	fenStringExampleTwo: [
		["bR", "", "bB", "", "bK", "", "bN", "bR"],
		["bP", "", "", "bP", "", "bP", "wN", "bP"],
		["bN", "", "", "wB", "", "", "", ""],
		["", "bP", "", "wN", "wP", "", "", "wP"],
		["", "", "", "", "", "", "wP", ""],
		["", "", "", "wP", "", "wQ", "", ""],
		["wP", "", "wP", "", "wK", "", "", ""],
		["bQ", "", "", "", "", "", "bB", ""],
	],
	START_OF_GAME_DEPTH_ONE_MOVES: 20,
	START_OF_GAME_DEPTH_TWO_MOVES: 400,
	START_OF_GAME_DEPTH_THREE_MOVES: 8902,
	START_OF_GAME_DEPTH_FOUR_MOVES: 197281,
	START_OF_GAME_DEPTH_FIVE_MOVES: 4865609,
	PERFT_POS_2_DEPTH_ONE_MOVES: 48,
	PERFT_POS_2_DEPTH_TWO_MOVES: 2039,
	PERFT_POS_2_DEPTH_THREE_MOVES: 97862,
	PERFT_POS_5_DEPTH_ONE_MOVES: 44,
	PERFT_POS_5_DEPTH_TWO_MOVES: 1486,
	PERFT_POS_5_DEPTH_THREE_MOVES: 62379,
	PERFT_POS_6_DEPTH_ONE_MOVES: 46,
	PERFT_POS_6_DEPTH_TWO_MOVES: 2079,
	PERFT_POS_6_DEPTH_THREE_MOVES: 89890,
};

export default testHelpers;
